name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # Setup Java 11 to be default (Sonar-scanner requirement as of 5.x)
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      # List compiled .class files to ensure they're available
      - name: List compiled .class files
        run: |
          echo "Listing compiled classes in target/classes"
          find target/classes -name "*.class"
          echo "Listing compiled classes in target/vprofile-v2/WEB-INF/classes"
          if [ -d "target/vprofile-v2/WEB-INF/classes" ]; then
            find target/vprofile-v2/WEB-INF/classes -name "*.class"
          else
            echo "Directory target/vprofile-v2/WEB-INF/classes does not exist."
          fi

      # Setup SonarQube
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Run sonar-scanner with debug logging enabled
      - name: SonarQube Scan
        run: |
          sonar-scanner -X \
            -Dsonar.host.url=${{ secrets.MY_SONAR_URL }} \
            -Dsonar.token=${{ secrets.MY_SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.MY_SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.MY_SONAR_PROJECT_KEY }} \
            -Dsonar.projectBaseDir=. \
            -Dsonar.sources=src/main/java \
            -Dsonar.junit.reportsPath=target/surefire-reports \
            -Dsonar.jacoco.reportPaths=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.exclusions=**/*Test.java \
            -Dsonar.java.binaries=target/classes
            -Dsonar.verbose=false  # Turn off verbose debug logging
            
