name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven Build
        run: mvn clean install  # Ensure compiled classes are generated

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      # Setup Java 11 to be default (SonarScanner requirement as of 5.x)
      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '11'

      # Setup SonarQube Scanner
      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Run SonarQube analysis
      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.MY_SONAR_URL }} \
            -Dsonar.token=${{ secrets.MY_SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.MY_SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.MY_SONAR_PROJECT_KEY }} \
            -Dsonar.projectBaseDir=. \
            -Dsonar.sources=src/main/java \
            -Dsonar.junit.reportsPath=target/surefire-reports \
            -Dsonar.jacoco.reportPaths=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.exclusions=**/*Test.java \
            -Dsonar.java.binaries=target/classes
