name: Hprofile Actions

on: workflow_dispatch

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Check compiled classes
        run: |
          echo "Looking for .class files in target/"
          find target/ -type f -name "*.class" || echo "No class files found!"

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup Sonar Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.MY_SONAR_URL }} \
            -Dsonar.token=${{ secrets.MY_SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.MY_SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.MY_SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src/main/java \
            -Dsonar.junit.reportsPath=target/surefire-reports \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
