name: Hprofile Actions

on:
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build project
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup SonarScanner
        uses: warchant/setup-sonar-scanner@v7

      name: Hprofile Actions

on:
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build project
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup SonarScanner
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.MY_SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.MY_SONAR_ORGANIZATION }} \
            -Dsonar.host.url=${{ secrets.MY_SONAR_URL }} \
            -Dsonar.login=${{ secrets.MY_SONAR_TOKEN }} \
            -Dsonar.sources=src/main/java \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.junit.reportsPath=target/surefire-reports \
            -Dsonar.jacoco.reportPaths=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml

      - name: Print compiled class files (optional debug)
        run: ls -R target/classes
