name: Hprofile Actions

on: 
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Set Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven (includes compile + test + coverage)
        run: mvn clean verify

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.MY_SONAR_URL }} \
            -Dsonar.token=${{ secrets.MY_SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.MY_SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.MY_SONAR_PROJECT_KEY }} \
            -Dsonar.projectBaseDir=hprofile \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.junit.reportsPath=target/surefire-reports \
            -Dsonar.jacoco.reportPaths=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/classes
