name: Hprofile Actions

on:
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven (compile, test, coverage)
        run: mvn clean verify
        working-directory: hprofile

      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
        working-directory: hprofile

      - name: Install SonarScanner
        uses: sonarsource/sonarcloud-github-action@master

      - name: Run SonarScanner
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.MY_SONAR_URL }} \
            -Dsonar.login=${{ secrets.MY_SONAR_TOKEN }} \
            -Dsonar.organization=${{ secrets.MY_SONAR_ORGANIZATION }} \
            -Dsonar.projectKey=${{ secrets.MY_SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src \
            -Dsonar.tests=src/test/java \
            -Dsonar.junit.reportsPath=target/surefire-reports \
            -Dsonar.jacoco.reportPaths=target/jacoco.exec \
            -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
            -Dsonar.java.binaries=target/classes
        working-directory: hprofile
